id: I9E8B81B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T18:25:18+00:00'
last_modified: '2022-06-08T07:52:29.493926+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD133163
  title: ཞེ་ཆེ་རྒྱལ་ཚབ་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ་གྱི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C3D1:
      image_group_id: I4PD2441
      title: ''
      total_pages: 530
      order: 1
      base_file: C3D1.txt
    65F2:
      image_group_id: I4PD2442
      title: ''
      total_pages: 490
      order: 2
      base_file: 65F2.txt
    8D8E:
      image_group_id: I4PD2443
      title: ''
      total_pages: 448
      order: 3
      base_file: 8D8E.txt
    BB24:
      image_group_id: I4PD2444
      title: ''
      total_pages: 528
      order: 4
      base_file: BB24.txt
    332C:
      image_group_id: I4PD2445
      title: ''
      total_pages: 486
      order: 5
      base_file: 332C.txt
    08CB:
      image_group_id: I4PD2446
      title: ''
      total_pages: 436
      order: 6
      base_file: 08CB.txt
    CD7B:
      image_group_id: I4PD2447
      title: ''
      total_pages: 496
      order: 7
      base_file: CD7B.txt
    FBA4:
      image_group_id: I4PD2448
      title: ''
      total_pages: 696
      order: 8
      base_file: FBA4.txt
    938E:
      image_group_id: I4PD2449
      title: ''
      total_pages: 658
      order: 9
      base_file: 938E.txt
    9BB4:
      image_group_id: I4PD2450
      title: ''
      total_pages: 572
      order: 10
      base_file: 9BB4.txt
    B94C:
      image_group_id: I4PD2451
      title: ''
      total_pages: 604
      order: 11
      base_file: B94C.txt
    FB1B:
      image_group_id: I4PD2452
      title: ''
      total_pages: 680
      order: 12
      base_file: FB1B.txt
    '2690':
      image_group_id: I4PD2453
      title: ''
      total_pages: 580
      order: 13
      base_file: 2690.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
